# Generated by Django 4.0.4 on 2022-05-31 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='codigo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.BigIntegerField(),
        ),
    ]
