# Generated by Django 4.0.4 on 2022-05-31 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0002_alter_libro_codigo_alter_usuario_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='numpags',
            field=models.IntegerField(),
        ),
    ]
